# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 442)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lineEditEnqueue = QtGui.QLineEdit(self.tab)
        self.lineEditEnqueue.setObjectName(_fromUtf8("lineEditEnqueue"))
        self.horizontalLayout_4.addWidget(self.lineEditEnqueue)
        self.btnEnqueue = QtGui.QPushButton(self.tab)
        self.btnEnqueue.setObjectName(_fromUtf8("btnEnqueue"))
        self.horizontalLayout_4.addWidget(self.btnEnqueue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lineEditDequeue = QtGui.QLineEdit(self.tab)
        self.lineEditDequeue.setObjectName(_fromUtf8("lineEditDequeue"))
        self.horizontalLayout_6.addWidget(self.lineEditDequeue)
        self.btnDequeue = QtGui.QPushButton(self.tab)
        self.btnDequeue.setObjectName(_fromUtf8("btnDequeue"))
        self.horizontalLayout_6.addWidget(self.btnDequeue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.btnClear = QtGui.QPushButton(self.tab)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.verticalLayout_3.addWidget(self.btnClear)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.lblStatus = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setMinimumSize(QtCore.QSize(300, 0))
        self.lblStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.horizontalLayout_3.addWidget(self.lblStatus)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.btnStartThr = QtGui.QPushButton(self.tab_2)
        self.btnStartThr.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnStartThr.setObjectName(_fromUtf8("btnStartThr"))
        self.verticalLayout_4.addWidget(self.btnStartThr)
        self.btnPauseThr = QtGui.QPushButton(self.tab_2)
        self.btnPauseThr.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnPauseThr.setObjectName(_fromUtf8("btnPauseThr"))
        self.verticalLayout_4.addWidget(self.btnPauseThr)
        self.btnResumeThr = QtGui.QPushButton(self.tab_2)
        self.btnResumeThr.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnResumeThr.setObjectName(_fromUtf8("btnResumeThr"))
        self.verticalLayout_4.addWidget(self.btnResumeThr)
        self.btnStopThr = QtGui.QPushButton(self.tab_2)
        self.btnStopThr.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnStopThr.setObjectName(_fromUtf8("btnStopThr"))
        self.verticalLayout_4.addWidget(self.btnStopThr)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.editResultThr = QtGui.QPlainTextEdit(self.tab_2)
        self.editResultThr.setObjectName(_fromUtf8("editResultThr"))
        self.horizontalLayout_8.addWidget(self.editResultThr)
        self.lblResultThr = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblResultThr.sizePolicy().hasHeightForWidth())
        self.lblResultThr.setSizePolicy(sizePolicy)
        self.lblResultThr.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblResultThr.setObjectName(_fromUtf8("lblResultThr"))
        self.horizontalLayout_8.addWidget(self.lblResultThr)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Options:", None))
        self.btnEnqueue.setText(_translate("MainWindow", "Enqueue", None))
        self.btnDequeue.setText(_translate("MainWindow", "Dequeue", None))
        self.btnClear.setText(_translate("MainWindow", "Clear", None))
        self.lblStatus.setText(_translate("MainWindow", "Status:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "CircularBuffer", None))
        self.label_2.setText(_translate("MainWindow", "Options:", None))
        self.btnStartThr.setText(_translate("MainWindow", "Start", None))
        self.btnPauseThr.setText(_translate("MainWindow", "Pause", None))
        self.btnResumeThr.setText(_translate("MainWindow", "Resume", None))
        self.btnStopThr.setText(_translate("MainWindow", "Stop", None))
        self.label_3.setText(_translate("MainWindow", "Resultado:", None))
        self.lblResultThr.setText(_translate("MainWindow", "Status:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "ThreadHandler", None))

