
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.Button button_lapis;
	
	private global::Gtk.Button button_retangulo;
	
	private global::Gtk.Button button_circulo;
	
	private global::Gtk.Button buttonClear;
	
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Label labelEspessura;
	
	private global::Gtk.HScale hscaleEspessura;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Label labelCor;
	
	private global::Gtk.ColorButton colorbuttonPincel;
	
	private global::Gtk.DrawingArea drawingareaDesenho;
	
	private global::Gtk.Statusbar statusbarMain;
	
	private global::Gtk.Label labelStatusTitle;
	
	private global::Gtk.Label labelStatusReal;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 320;
		this.HeightRequest = 240;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Paint do Italo");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button_lapis = new global::Gtk.Button ();
		this.button_lapis.CanFocus = true;
		this.button_lapis.Name = "button_lapis";
		this.button_lapis.UseUnderline = true;
		this.button_lapis.Label = global::Mono.Unix.Catalog.GetString ("_Lápis");
		global::Gtk.Image w1 = new global::Gtk.Image ();
		w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Button);
		this.button_lapis.Image = w1;
		this.vbox3.Add (this.button_lapis);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button_lapis]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button_retangulo = new global::Gtk.Button ();
		this.button_retangulo.WidthRequest = 109;
		this.button_retangulo.CanFocus = true;
		this.button_retangulo.Name = "button_retangulo";
		this.button_retangulo.UseUnderline = true;
		this.button_retangulo.Label = global::Mono.Unix.Catalog.GetString ("Retângulo");
		this.vbox3.Add (this.button_retangulo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button_retangulo]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button_circulo = new global::Gtk.Button ();
		this.button_circulo.CanFocus = true;
		this.button_circulo.Name = "button_circulo";
		this.button_circulo.UseUnderline = true;
		this.button_circulo.Label = global::Mono.Unix.Catalog.GetString ("Círculo");
		this.vbox3.Add (this.button_circulo);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.button_circulo]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.buttonClear = new global::Gtk.Button ();
		this.buttonClear.CanFocus = true;
		this.buttonClear.Name = "buttonClear";
		this.buttonClear.UseUnderline = true;
		this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Limpar");
		this.vbox3.Add (this.buttonClear);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.buttonClear]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.labelEspessura = new global::Gtk.Label ();
		this.labelEspessura.Name = "labelEspessura";
		this.labelEspessura.Xalign = 0F;
		this.labelEspessura.LabelProp = global::Mono.Unix.Catalog.GetString ("Espessura: 1.00");
		this.vbox5.Add (this.labelEspessura);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.labelEspessura]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hscaleEspessura = new global::Gtk.HScale (null);
		this.hscaleEspessura.WidthRequest = 150;
		this.hscaleEspessura.CanFocus = true;
		this.hscaleEspessura.Name = "hscaleEspessura";
		this.hscaleEspessura.Adjustment.Lower = 0.1;
		this.hscaleEspessura.Adjustment.Upper = 50;
		this.hscaleEspessura.Adjustment.PageIncrement = 0.1;
		this.hscaleEspessura.Adjustment.StepIncrement = 1;
		this.hscaleEspessura.Adjustment.Value = 1;
		this.hscaleEspessura.DrawValue = true;
		this.hscaleEspessura.Digits = 0;
		this.hscaleEspessura.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox5.Add (this.hscaleEspessura);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hscaleEspessura]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox3.Add (this.vbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
		w8.Position = 4;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelCor = new global::Gtk.Label ();
		this.labelCor.Name = "labelCor";
		this.labelCor.Xalign = 0F;
		this.labelCor.LabelProp = global::Mono.Unix.Catalog.GetString ("Cor:");
		this.vbox1.Add (this.labelCor);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelCor]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.colorbuttonPincel = new global::Gtk.ColorButton ();
		this.colorbuttonPincel.CanFocus = true;
		this.colorbuttonPincel.Events = ((global::Gdk.EventMask)(784));
		this.colorbuttonPincel.Name = "colorbuttonPincel";
		this.vbox1.Add (this.colorbuttonPincel);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.colorbuttonPincel]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox3.Add (this.vbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox1]));
		w11.Position = 5;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.drawingareaDesenho = new global::Gtk.DrawingArea ();
		this.drawingareaDesenho.WidthRequest = 100;
		this.drawingareaDesenho.HeightRequest = 100;
		this.drawingareaDesenho.Name = "drawingareaDesenho";
		this.hbox2.Add (this.drawingareaDesenho);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.drawingareaDesenho]));
		w13.Position = 1;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w14.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbarMain = new global::Gtk.Statusbar ();
		this.statusbarMain.Name = "statusbarMain";
		this.statusbarMain.Spacing = 6;
		// Container child statusbarMain.Gtk.Box+BoxChild
		this.labelStatusTitle = new global::Gtk.Label ();
		this.labelStatusTitle.Name = "labelStatusTitle";
		this.labelStatusTitle.Xalign = 0F;
		this.labelStatusTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Status:");
		this.statusbarMain.Add (this.labelStatusTitle);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.statusbarMain [this.labelStatusTitle]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child statusbarMain.Gtk.Box+BoxChild
		this.labelStatusReal = new global::Gtk.Label ();
		this.labelStatusReal.Name = "labelStatusReal";
		this.labelStatusReal.Xalign = 0F;
		this.labelStatusReal.LabelProp = global::Mono.Unix.Catalog.GetString ("Aguardando...");
		this.statusbarMain.Add (this.labelStatusReal);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.statusbarMain [this.labelStatusReal]));
		w16.Position = 2;
		w16.Fill = false;
		this.vbox2.Add (this.statusbarMain);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbarMain]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w18.Position = 0;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 799;
		this.DefaultHeight = 461;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnButtonReleaseEvent);
		this.button_lapis.Clicked += new global::System.EventHandler (this.OnButtonLapisClicked);
		this.button_retangulo.Clicked += new global::System.EventHandler (this.OnButtonRetanguloClicked);
		this.button_circulo.Clicked += new global::System.EventHandler (this.OnButtonCirculoClicked);
		this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		this.hscaleEspessura.ValueChanged += new global::System.EventHandler (this.OnHscaleEspessuraValueChanged);
		this.colorbuttonPincel.ColorSet += new global::System.EventHandler (this.OnColorbuttonPincelColorSet);
		this.drawingareaDesenho.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDrawingareaDesenhoButtonPressEvent);
		this.drawingareaDesenho.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDrawingareaDesenhoButtonReleaseEvent);
		this.drawingareaDesenho.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDrawingareaDesenhoMotionNotifyEvent);
	}
}
